// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCEZjIV-e1cT8EeWF_CUqb5sFopdU5kk',
    appId: '1:255338468070:web:64ba8a2d6f70e8668ea127',
    messagingSenderId: '255338468070',
    projectId: 'nappy-61690',
    authDomain: 'nappy-61690.firebaseapp.com',
    storageBucket: 'nappy-61690.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJG6kQJut3GMAzc4vGTNC5XcCyR5XEG4U',
    appId: '1:255338468070:android:155937292527e46a8ea127',
    messagingSenderId: '255338468070',
    projectId: 'nappy-61690',
    storageBucket: 'nappy-61690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWD16oz8q-I5pQLjc8z-bq0kjjGOotKo0',
    appId: '1:255338468070:ios:bd09342613252c1e8ea127',
    messagingSenderId: '255338468070',
    projectId: 'nappy-61690',
    storageBucket: 'nappy-61690.appspot.com',
    iosClientId: '255338468070-c14v0606e56509dsu5vls9qn85lccgen.apps.googleusercontent.com',
    iosBundleId: 'com.example.nappyMobile',
  );
}
